///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SubmissionCase_E2E
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Adverse1_Owner_Personal_Information_Save recording.
    /// </summary>
    [TestModule("25b3ed7c-4d79-4cda-b731-c72cbf189654", ModuleType.Recording, 1)]
    public partial class Adverse1_Owner_Personal_Information_Save : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SubmissionCase_E2ERepository repository.
        /// </summary>
        public static SubmissionCase_E2ERepository repo = SubmissionCase_E2ERepository.Instance;

        static Adverse1_Owner_Personal_Information_Save instance = new Adverse1_Owner_Personal_Information_Save();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Adverse1_Owner_Personal_Information_Save()
        {
            AO_PI_FirstName = "";
            AO_PI_LastName = "";
            AO_PI_BusinessName = "";
            AO_PI_Address1 = "";
            AO_PI_Address2 = "";
            AO_PI_City = "";
            AO_PI_USStateCode = "";
            AO_PI_ZipCode = "";
            AO_PI_Email_getValue = "";
            AO_PI_BankruptcyCounty = "";
            AO_PI_BankruptcyDistrict = "";
            AO_PI_BankruptcyChapter = "";
            AO_PI_BankruptcyCaseNo = "";
            AO_PI_PhoneUseType_getValue = "";
            AO_PI_PhoneType_getValue = "";
            AO_PI_PhoneSource_getValue = "";
            AO_PI_PhoneNumber_getValue = "";
            AO_PI_EmailUseType_getValue = "";
            AO_PI_EmailSource_getValue = "";
            AO_PI_EmailID_getValue = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Adverse1_Owner_Personal_Information_Save Instance
        {
            get { return instance; }
        }

#region Variables

        string _AO_PI_FirstName;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_FirstName.
        /// </summary>
        [TestVariable("fb31d464-b0f8-472e-bcbe-c3258cf7cfc4")]
        public string AO_PI_FirstName
        {
            get { return _AO_PI_FirstName; }
            set { _AO_PI_FirstName = value; }
        }

        string _AO_PI_LastName;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_LastName.
        /// </summary>
        [TestVariable("2cb0035f-55db-4a65-b9a8-b6dcf4b44746")]
        public string AO_PI_LastName
        {
            get { return _AO_PI_LastName; }
            set { _AO_PI_LastName = value; }
        }

        string _AO_PI_BusinessName;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_BusinessName.
        /// </summary>
        [TestVariable("5859a485-a08a-4689-8744-5b2449815c1f")]
        public string AO_PI_BusinessName
        {
            get { return _AO_PI_BusinessName; }
            set { _AO_PI_BusinessName = value; }
        }

        string _AO_PI_Address1;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_Address1.
        /// </summary>
        [TestVariable("49a11856-e062-4173-9b5f-9ae6e64c5365")]
        public string AO_PI_Address1
        {
            get { return _AO_PI_Address1; }
            set { _AO_PI_Address1 = value; }
        }

        string _AO_PI_Address2;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_Address2.
        /// </summary>
        [TestVariable("1b813a02-9027-41a5-847d-150ec200c0f3")]
        public string AO_PI_Address2
        {
            get { return _AO_PI_Address2; }
            set { _AO_PI_Address2 = value; }
        }

        string _AO_PI_City;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_City.
        /// </summary>
        [TestVariable("db22f0a3-1adc-40fa-8e76-212bb208ceee")]
        public string AO_PI_City
        {
            get { return _AO_PI_City; }
            set { _AO_PI_City = value; }
        }

        string _AO_PI_USStateCode;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_USStateCode.
        /// </summary>
        [TestVariable("158355e5-166e-4fe3-8ca0-3ab9aa38599b")]
        public string AO_PI_USStateCode
        {
            get { return _AO_PI_USStateCode; }
            set { _AO_PI_USStateCode = value; }
        }

        string _AO_PI_ZipCode;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_ZipCode.
        /// </summary>
        [TestVariable("f8e57883-d76a-4404-964e-9d66926a8be2")]
        public string AO_PI_ZipCode
        {
            get { return _AO_PI_ZipCode; }
            set { _AO_PI_ZipCode = value; }
        }

        string _AO_PI_Email_getValue;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_Email_getValue.
        /// </summary>
        [TestVariable("7398d2a9-350c-47e5-ba1c-85599060043f")]
        public string AO_PI_Email_getValue
        {
            get { return _AO_PI_Email_getValue; }
            set { _AO_PI_Email_getValue = value; }
        }

        string _AO_PI_BankruptcyCounty;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_BankruptcyCounty.
        /// </summary>
        [TestVariable("04f8ecc5-8bc9-4214-9442-67a255f15bef")]
        public string AO_PI_BankruptcyCounty
        {
            get { return _AO_PI_BankruptcyCounty; }
            set { _AO_PI_BankruptcyCounty = value; }
        }

        string _AO_PI_BankruptcyDistrict;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_BankruptcyDistrict.
        /// </summary>
        [TestVariable("1a6d3a62-1f70-46a2-8b4a-d5def196f8ce")]
        public string AO_PI_BankruptcyDistrict
        {
            get { return _AO_PI_BankruptcyDistrict; }
            set { _AO_PI_BankruptcyDistrict = value; }
        }

        string _AO_PI_BankruptcyChapter;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_BankruptcyChapter.
        /// </summary>
        [TestVariable("5a12872c-83e1-4633-8758-c0734a71df16")]
        public string AO_PI_BankruptcyChapter
        {
            get { return _AO_PI_BankruptcyChapter; }
            set { _AO_PI_BankruptcyChapter = value; }
        }

        string _AO_PI_BankruptcyCaseNo;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_BankruptcyCaseNo.
        /// </summary>
        [TestVariable("39d7de37-500a-404d-b4f1-ebfeff9860fa")]
        public string AO_PI_BankruptcyCaseNo
        {
            get { return _AO_PI_BankruptcyCaseNo; }
            set { _AO_PI_BankruptcyCaseNo = value; }
        }

        string _AO_PI_PhoneUseType_getValue;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_PhoneUseType_getValue.
        /// </summary>
        [TestVariable("a17a5d8f-c3a0-456f-a81f-23b633c7e2f5")]
        public string AO_PI_PhoneUseType_getValue
        {
            get { return _AO_PI_PhoneUseType_getValue; }
            set { _AO_PI_PhoneUseType_getValue = value; }
        }

        string _AO_PI_PhoneType_getValue;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_PhoneType_getValue.
        /// </summary>
        [TestVariable("38db9dd8-92ef-40c4-90f2-b3f109e84290")]
        public string AO_PI_PhoneType_getValue
        {
            get { return _AO_PI_PhoneType_getValue; }
            set { _AO_PI_PhoneType_getValue = value; }
        }

        string _AO_PI_PhoneSource_getValue;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_PhoneSource_getValue.
        /// </summary>
        [TestVariable("33433a79-27ed-4ccc-a9ac-c54051340214")]
        public string AO_PI_PhoneSource_getValue
        {
            get { return _AO_PI_PhoneSource_getValue; }
            set { _AO_PI_PhoneSource_getValue = value; }
        }

        string _AO_PI_PhoneNumber_getValue;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_PhoneNumber_getValue.
        /// </summary>
        [TestVariable("81a94c6b-0554-4ec4-b374-79dbe0b556d4")]
        public string AO_PI_PhoneNumber_getValue
        {
            get { return _AO_PI_PhoneNumber_getValue; }
            set { _AO_PI_PhoneNumber_getValue = value; }
        }

        string _AO_PI_EmailUseType_getValue;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_EmailUseType_getValue.
        /// </summary>
        [TestVariable("a31ce95b-2841-4f29-8745-c422adfa5693")]
        public string AO_PI_EmailUseType_getValue
        {
            get { return _AO_PI_EmailUseType_getValue; }
            set { _AO_PI_EmailUseType_getValue = value; }
        }

        string _AO_PI_EmailSource_getValue;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_EmailSource_getValue.
        /// </summary>
        [TestVariable("e5205e3e-9e42-492a-a294-9005e175937b")]
        public string AO_PI_EmailSource_getValue
        {
            get { return _AO_PI_EmailSource_getValue; }
            set { _AO_PI_EmailSource_getValue = value; }
        }

        string _AO_PI_EmailID_getValue;

        /// <summary>
        /// Gets or sets the value of variable AO_PI_EmailID_getValue.
        /// </summary>
        [TestVariable("70569d56-6eb9-4124-a453-21ccb1a33aa0")]
        public string AO_PI_EmailID_getValue
        {
            get { return _AO_PI_EmailID_getValue; }
            set { _AO_PI_EmailID_getValue = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Save_Button' at 6;8.", repo.ApplicationUnderTest.Save_ButtonInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Save_Button.Click("6;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(1));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_FirstName) on item 'ApplicationUnderTest.AO_PI_FirstName'.", repo.ApplicationUnderTest.AO_PI_FirstNameInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_FirstNameInfo, "TagValue", AO_PI_FirstName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_FirstName, new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_LastName) on item 'ApplicationUnderTest.AO_PI_LastName'.", repo.ApplicationUnderTest.AO_PI_LastNameInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_LastNameInfo, "TagValue", AO_PI_LastName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_LastName, new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_BusinessName) on item 'ApplicationUnderTest.AO_PI_BusinessName'.", repo.ApplicationUnderTest.AO_PI_BusinessNameInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_BusinessNameInfo, "TagValue", AO_PI_BusinessName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_BusinessName, new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_Address1) on item 'ApplicationUnderTest.AO_PI_Address1'.", repo.ApplicationUnderTest.AO_PI_Address1Info, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_Address1Info, "TagValue", AO_PI_Address1);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_Address1, new RecordItemIndex(9));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_Address2) on item 'ApplicationUnderTest.AO_PI_Address2'.", repo.ApplicationUnderTest.AO_PI_Address2Info, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_Address2Info, "TagValue", AO_PI_Address2);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_Address2, new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_City) on item 'ApplicationUnderTest.AO_PI_City'.", repo.ApplicationUnderTest.AO_PI_CityInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_CityInfo, "TagValue", AO_PI_City);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_City, new RecordItemIndex(13));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_USStateCode) on item 'ApplicationUnderTest.AO_PI_USStateCode'.", repo.ApplicationUnderTest.AO_PI_USStateCodeInfo, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_USStateCodeInfo, "TagValue", AO_PI_USStateCode);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_USStateCode, new RecordItemIndex(15));
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_ZipCode' and assigning its value to variable 'AO_PI_ZipCode'.", repo.ApplicationUnderTest.AO_PI_ZipCodeInfo, new RecordItemIndex(16));
            //AO_PI_ZipCode = repo.ApplicationUnderTest.AO_PI_ZipCode.Element.GetAttributeValueText("TagValue");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_ZipCode) on item 'ApplicationUnderTest.AO_PI_ZipCode'.", repo.ApplicationUnderTest.AO_PI_ZipCodeInfo, new RecordItemIndex(17));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_ZipCodeInfo, "TagValue", AO_PI_ZipCode);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_ZipCode, new RecordItemIndex(18));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AO_PI_PhoneUseType' at Center.", repo.ApplicationUnderTest.AO_PI_PhoneUseTypeInfo, new RecordItemIndex(19));
            repo.ApplicationUnderTest.AO_PI_PhoneUseType.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_Email' and assigning its value to variable 'AO_PI_Email_getValue'.", repo.ApplicationUnderTest.AO_PI_EmailInfo, new RecordItemIndex(20));
            //AO_PI_Email_getValue = repo.ApplicationUnderTest.AO_PI_Email.Element.GetAttributeValueText("TagValue");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "User", AO_PI_Email_getValue, new RecordItemIndex(21));
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(22));
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_Email_getValue) on item 'ApplicationUnderTest.AO_PI_Email'.", repo.ApplicationUnderTest.AO_PI_EmailInfo, new RecordItemIndex(23));
            //Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_EmailInfo, "TagValue", AO_PI_Email_getValue);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'ApplicationUnderTest.OAT_PI_Returned_Mail'.", repo.ApplicationUnderTest.OAT_PI_Returned_MailInfo, new RecordItemIndex(24));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_Returned_MailInfo, "Checked", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='true') on item 'ApplicationUnderTest.OAT_PI_Returned_Mail'.", repo.ApplicationUnderTest.OAT_PI_Returned_MailInfo, new RecordItemIndex(25));
            Validate.AttributeEqual(repo.ApplicationUnderTest.OAT_PI_Returned_MailInfo, "Value", "true");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_BankruptcyCounty' and assigning its value to variable 'AO_PI_BankruptcyCounty'.", repo.ApplicationUnderTest.AO_PI_BankruptcyCountyInfo, new RecordItemIndex(26));
            //AO_PI_BankruptcyCounty = repo.ApplicationUnderTest.AO_PI_BankruptcyCounty.Element.GetAttributeValueText("TagValue");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_BankruptcyCounty) on item 'ApplicationUnderTest.AO_PI_BankruptcyCounty'.", repo.ApplicationUnderTest.AO_PI_BankruptcyCountyInfo, new RecordItemIndex(27));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_BankruptcyCountyInfo, "TagValue", AO_PI_BankruptcyCounty);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_BankruptcyCounty, new RecordItemIndex(28));
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_BankruptcyDistrict' and assigning its value to variable 'AO_PI_BankruptcyDistrict'.", repo.ApplicationUnderTest.AO_PI_BankruptcyDistrictInfo, new RecordItemIndex(29));
            //AO_PI_BankruptcyDistrict = repo.ApplicationUnderTest.AO_PI_BankruptcyDistrict.Element.GetAttributeValueText("TagValue");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_BankruptcyDistrict) on item 'ApplicationUnderTest.AO_PI_BankruptcyDistrict'.", repo.ApplicationUnderTest.AO_PI_BankruptcyDistrictInfo, new RecordItemIndex(30));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_BankruptcyDistrictInfo, "TagValue", AO_PI_BankruptcyDistrict);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_BankruptcyDistrict, new RecordItemIndex(31));
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_BankruptcyChapter' and assigning its value to variable 'AO_PI_BankruptcyChapter'.", repo.ApplicationUnderTest.AO_PI_BankruptcyChapterInfo, new RecordItemIndex(32));
            //AO_PI_BankruptcyChapter = repo.ApplicationUnderTest.AO_PI_BankruptcyChapter.Element.GetAttributeValueText("TagValue");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_BankruptcyChapter) on item 'ApplicationUnderTest.AO_PI_BankruptcyChapter'.", repo.ApplicationUnderTest.AO_PI_BankruptcyChapterInfo, new RecordItemIndex(33));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_BankruptcyChapterInfo, "TagValue", AO_PI_BankruptcyChapter);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_BankruptcyChapter, new RecordItemIndex(34));
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_BankruptcyCaseNo' and assigning its value to variable 'AO_PI_BankruptcyCaseNo'.", repo.ApplicationUnderTest.AO_PI_BankruptcyCaseNoInfo, new RecordItemIndex(35));
            //AO_PI_BankruptcyCaseNo = repo.ApplicationUnderTest.AO_PI_BankruptcyCaseNo.Element.GetAttributeValueText("TagValue");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_BankruptcyCaseNo) on item 'ApplicationUnderTest.AO_PI_BankruptcyCaseNo'.", repo.ApplicationUnderTest.AO_PI_BankruptcyCaseNoInfo, new RecordItemIndex(36));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_BankruptcyCaseNoInfo, "TagValue", AO_PI_BankruptcyCaseNo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_BankruptcyCaseNo, new RecordItemIndex(37));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_PhoneUseType' and assigning its value to variable 'AO_PI_PhoneUseType_getValue'.", repo.ApplicationUnderTest.AO_PI_PhoneUseTypeInfo, new RecordItemIndex(38));
            AO_PI_PhoneUseType_getValue = repo.ApplicationUnderTest.AO_PI_PhoneUseType.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_PhoneUseType_getValue) on item 'ApplicationUnderTest.AO_PI_PhoneUseType'.", repo.ApplicationUnderTest.AO_PI_PhoneUseTypeInfo, new RecordItemIndex(39));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_PhoneUseTypeInfo, "TagValue", AO_PI_PhoneUseType_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_PhoneUseType_getValue, new RecordItemIndex(40));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_PhoneType' and assigning its value to variable 'AO_PI_PhoneType_getValue'.", repo.ApplicationUnderTest.AO_PI_PhoneTypeInfo, new RecordItemIndex(41));
            AO_PI_PhoneType_getValue = repo.ApplicationUnderTest.AO_PI_PhoneType.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_PhoneType_getValue) on item 'ApplicationUnderTest.AO_PI_PhoneType'.", repo.ApplicationUnderTest.AO_PI_PhoneTypeInfo, new RecordItemIndex(42));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_PhoneTypeInfo, "TagValue", AO_PI_PhoneType_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_PhoneType_getValue, new RecordItemIndex(43));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_PhoneSource' and assigning its value to variable 'AO_PI_PhoneSource_getValue'.", repo.ApplicationUnderTest.AO_PI_PhoneSourceInfo, new RecordItemIndex(44));
            AO_PI_PhoneSource_getValue = repo.ApplicationUnderTest.AO_PI_PhoneSource.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_PhoneSource_getValue) on item 'ApplicationUnderTest.AO_PI_PhoneSource'.", repo.ApplicationUnderTest.AO_PI_PhoneSourceInfo, new RecordItemIndex(45));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_PhoneSourceInfo, "TagValue", AO_PI_PhoneSource_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_PhoneSource_getValue, new RecordItemIndex(46));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_PhoneNumber' and assigning its value to variable 'AO_PI_PhoneNumber_getValue'.", repo.ApplicationUnderTest.AO_PI_PhoneNumberInfo, new RecordItemIndex(47));
            AO_PI_PhoneNumber_getValue = repo.ApplicationUnderTest.AO_PI_PhoneNumber.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_PhoneNumber_getValue) on item 'ApplicationUnderTest.AO_PI_PhoneNumber'.", repo.ApplicationUnderTest.AO_PI_PhoneNumberInfo, new RecordItemIndex(48));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_PhoneNumberInfo, "TagValue", AO_PI_PhoneNumber_getValue);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_PhoneNumber_getValue, new RecordItemIndex(49));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_EmailUseType' and assigning its value to variable 'AO_PI_EmailUseType_getValue'.", repo.ApplicationUnderTest.AO_PI_EmailUseTypeInfo, new RecordItemIndex(50));
            AO_PI_EmailUseType_getValue = repo.ApplicationUnderTest.AO_PI_EmailUseType.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_EmailUseType_getValue) on item 'ApplicationUnderTest.AO_PI_EmailUseType'.", repo.ApplicationUnderTest.AO_PI_EmailUseTypeInfo, new RecordItemIndex(51));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_EmailUseTypeInfo, "TagValue", AO_PI_EmailUseType_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_FirstName, new RecordItemIndex(52));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_EmailSource' and assigning its value to variable 'AO_PI_EmailSource_getValue'.", repo.ApplicationUnderTest.AO_PI_EmailSourceInfo, new RecordItemIndex(53));
            AO_PI_EmailSource_getValue = repo.ApplicationUnderTest.AO_PI_EmailSource.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_EmailSource_getValue) on item 'ApplicationUnderTest.AO_PI_EmailSource'.", repo.ApplicationUnderTest.AO_PI_EmailSourceInfo, new RecordItemIndex(54));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_EmailSourceInfo, "TagValue", AO_PI_EmailSource_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_EmailSource_getValue, new RecordItemIndex(55));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'ApplicationUnderTest.AO_PI_EmailID' and assigning its value to variable 'AO_PI_EmailID_getValue'.", repo.ApplicationUnderTest.AO_PI_EmailIDInfo, new RecordItemIndex(56));
            AO_PI_EmailID_getValue = repo.ApplicationUnderTest.AO_PI_EmailID.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue=$AO_PI_EmailID_getValue) on item 'ApplicationUnderTest.AO_PI_EmailID'.", repo.ApplicationUnderTest.AO_PI_EmailIDInfo, new RecordItemIndex(57));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AO_PI_EmailIDInfo, "TagValue", AO_PI_EmailID_getValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AO_PI_EmailID_getValue, new RecordItemIndex(58));
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$AO_PI_PhoneUseType_getValue' on item 'ApplicationUnderTest.AO_PI_PhoneUseType'.", repo.ApplicationUnderTest.AO_PI_PhoneUseTypeInfo, new RecordItemIndex(59));
            //repo.ApplicationUnderTest.AO_PI_PhoneUseType.Element.SetAttributeValue("TagValue", AO_PI_PhoneUseType_getValue);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$AO_PI_PhoneType_getValue' on item 'ApplicationUnderTest.AO_PI_PhoneType'.", repo.ApplicationUnderTest.AO_PI_PhoneTypeInfo, new RecordItemIndex(60));
            //repo.ApplicationUnderTest.AO_PI_PhoneType.Element.SetAttributeValue("TagValue", AO_PI_PhoneType_getValue);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$AO_PI_PhoneSource_getValue' on item 'ApplicationUnderTest.AO_PI_PhoneSource'.", repo.ApplicationUnderTest.AO_PI_PhoneSourceInfo, new RecordItemIndex(61));
            //repo.ApplicationUnderTest.AO_PI_PhoneSource.Element.SetAttributeValue("TagValue", AO_PI_PhoneSource_getValue);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$AO_PI_PhoneNumber_getValue' with focus on 'ApplicationUnderTest.AO_PI_PhoneNumber'.", repo.ApplicationUnderTest.AO_PI_PhoneNumberInfo, new RecordItemIndex(62));
            //repo.ApplicationUnderTest.AO_PI_PhoneNumber.PressKeys(AO_PI_PhoneNumber_getValue);
            //Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.PegaCaseManagerPortalGoogleChrome.Screenshot_Window, false, new RecordItemIndex(63));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SubmitButton1' at 46;15.", repo.ApplicationUnderTest.SubmitButton1Info, new RecordItemIndex(64));
            repo.ApplicationUnderTest.SubmitButton1.Click("46;15");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
