///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SubmissionCase_E2E
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Edit_Adverse1_Driver_FooterMapping recording.
    /// </summary>
    [TestModule("3a1479ed-1b05-458f-8dae-f5107f5f2987", ModuleType.Recording, 1)]
    public partial class Edit_Adverse1_Driver_FooterMapping : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SubmissionCase_E2ERepository repository.
        /// </summary>
        public static SubmissionCase_E2ERepository repo = SubmissionCase_E2ERepository.Instance;

        static Edit_Adverse1_Driver_FooterMapping instance = new Edit_Adverse1_Driver_FooterMapping();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Edit_Adverse1_Driver_FooterMapping()
        {
            AD1_PI_FirstName = "";
            AD1_PI_LastName = "";
            AD1_PI_Address1 = "";
            AD1_PI_Address2 = "";
            AD1_PI_City = "";
            AD1_PI_State = "";
            AD1_PI_Zip = "";
            AD1_PI_POE = "";
            AD1_PI_BankruptcyCounty = "";
            AD1_PI_BankruptcyDistrict = "";
            AD1_PI_BankruptcyChapter = "";
            AD1_PI_BankruptcyCaseNo = "";
            AD1_PI_Personal = "";
            AD1_PI_PhoneType_LandLine = "";
            AD1_PI_Direct = "";
            AD1_PI_PhoneNumber_Value = "";
            AD1_LI_CompanyName = "";
            AD1_LI_PolicyNumber = "";
            AD1_LI_ClaimNumber = "";
            AD1_LI_ContactName = "";
            AD1_LI_USStateCode = "";
            AD1_LI_Address1 = "";
            AD1_LI_Address2 = "";
            AD1_LI_ZipCode = "";
            AD1_LI_City = "";
            AD1_LI_PhoneUseType = "";
            AD1_LI_PhoneType = "";
            AD1_LI_PhoneSource = "";
            AD1_LI_PhoneNumber = "";
            AD1_LI_DOB = "";
            AD1_LI_LicenseNumber = "";
            AD1_LI_DriversLicenseState = "";
            AD1_LI_RevocationDate = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Edit_Adverse1_Driver_FooterMapping Instance
        {
            get { return instance; }
        }

#region Variables

        string _AD1_PI_FirstName;

        /// <summary>
        /// Gets or sets the value of variable AD1_PI_FirstName.
        /// </summary>
        [TestVariable("33dd6d9f-7c3f-4b55-9ea9-2e982ca2b41a")]
        public string AD1_PI_FirstName
        {
            get { return _AD1_PI_FirstName; }
            set { _AD1_PI_FirstName = value; }
        }

        string _AD1_PI_LastName;

        /// <summary>
        /// Gets or sets the value of variable AD1_PI_LastName.
        /// </summary>
        [TestVariable("bd52f8ec-a37a-45b1-aa3f-36e0ef560084")]
        public string AD1_PI_LastName
        {
            get { return _AD1_PI_LastName; }
            set { _AD1_PI_LastName = value; }
        }

        string _AD1_PI_Address1;

        /// <summary>
        /// Gets or sets the value of variable AD1_PI_Address1.
        /// </summary>
        [TestVariable("749af84f-9697-4ebb-aa05-cf08abdf192d")]
        public string AD1_PI_Address1
        {
            get { return _AD1_PI_Address1; }
            set { _AD1_PI_Address1 = value; }
        }

        string _AD1_PI_Address2;

        /// <summary>
        /// Gets or sets the value of variable AD1_PI_Address2.
        /// </summary>
        [TestVariable("a9b708e7-ae8b-4c31-a387-60c27acea187")]
        public string AD1_PI_Address2
        {
            get { return _AD1_PI_Address2; }
            set { _AD1_PI_Address2 = value; }
        }

        string _AD1_PI_City;

        /// <summary>
        /// Gets or sets the value of variable AD1_PI_City.
        /// </summary>
        [TestVariable("03010cf9-2c4c-43db-8427-d90a941ff205")]
        public string AD1_PI_City
        {
            get { return _AD1_PI_City; }
            set { _AD1_PI_City = value; }
        }

        string _AD1_PI_State;

        /// <summary>
        /// Gets or sets the value of variable AD1_PI_State.
        /// </summary>
        [TestVariable("e8cf107c-30a3-4966-8864-b67416a2e592")]
        public string AD1_PI_State
        {
            get { return _AD1_PI_State; }
            set { _AD1_PI_State = value; }
        }

        string _AD1_PI_Zip;

        /// <summary>
        /// Gets or sets the value of variable AD1_PI_Zip.
        /// </summary>
        [TestVariable("b9a03f82-b769-4393-8c21-a0f3fa40123e")]
        public string AD1_PI_Zip
        {
            get { return _AD1_PI_Zip; }
            set { _AD1_PI_Zip = value; }
        }

        string _AD1_PI_POE;

        /// <summary>
        /// Gets or sets the value of variable AD1_PI_POE.
        /// </summary>
        [TestVariable("8ec491b7-81fb-4e69-9245-cee42ebb78ee")]
        public string AD1_PI_POE
        {
            get { return _AD1_PI_POE; }
            set { _AD1_PI_POE = value; }
        }

        string _AD1_PI_BankruptcyCounty;

        /// <summary>
        /// Gets or sets the value of variable AD1_PI_BankruptcyCounty.
        /// </summary>
        [TestVariable("5a59b8d5-c157-40f2-854b-9d3131bc44c8")]
        public string AD1_PI_BankruptcyCounty
        {
            get { return _AD1_PI_BankruptcyCounty; }
            set { _AD1_PI_BankruptcyCounty = value; }
        }

        string _AD1_PI_BankruptcyDistrict;

        /// <summary>
        /// Gets or sets the value of variable AD1_PI_BankruptcyDistrict.
        /// </summary>
        [TestVariable("c63b0d52-5233-4d05-957e-a98c4c514990")]
        public string AD1_PI_BankruptcyDistrict
        {
            get { return _AD1_PI_BankruptcyDistrict; }
            set { _AD1_PI_BankruptcyDistrict = value; }
        }

        string _AD1_PI_BankruptcyChapter;

        /// <summary>
        /// Gets or sets the value of variable AD1_PI_BankruptcyChapter.
        /// </summary>
        [TestVariable("8530a397-7cdb-40b5-94cd-79020bdb34d5")]
        public string AD1_PI_BankruptcyChapter
        {
            get { return _AD1_PI_BankruptcyChapter; }
            set { _AD1_PI_BankruptcyChapter = value; }
        }

        string _AD1_PI_BankruptcyCaseNo;

        /// <summary>
        /// Gets or sets the value of variable AD1_PI_BankruptcyCaseNo.
        /// </summary>
        [TestVariable("9bcd9009-788b-4e0a-8d70-06c3470f72ad")]
        public string AD1_PI_BankruptcyCaseNo
        {
            get { return _AD1_PI_BankruptcyCaseNo; }
            set { _AD1_PI_BankruptcyCaseNo = value; }
        }

        string _AD1_PI_Personal;

        /// <summary>
        /// Gets or sets the value of variable AD1_PI_Personal.
        /// </summary>
        [TestVariable("c6008378-6e0b-416e-bf73-42886c93da6f")]
        public string AD1_PI_Personal
        {
            get { return _AD1_PI_Personal; }
            set { _AD1_PI_Personal = value; }
        }

        string _AD1_PI_PhoneType_LandLine;

        /// <summary>
        /// Gets or sets the value of variable AD1_PI_PhoneType_LandLine.
        /// </summary>
        [TestVariable("bd936a6f-6496-403a-bba9-a9732f7d872b")]
        public string AD1_PI_PhoneType_LandLine
        {
            get { return _AD1_PI_PhoneType_LandLine; }
            set { _AD1_PI_PhoneType_LandLine = value; }
        }

        string _AD1_PI_Direct;

        /// <summary>
        /// Gets or sets the value of variable AD1_PI_Direct.
        /// </summary>
        [TestVariable("1368c69b-f530-46e8-b624-6d39c05845c7")]
        public string AD1_PI_Direct
        {
            get { return _AD1_PI_Direct; }
            set { _AD1_PI_Direct = value; }
        }

        string _AD1_PI_PhoneNumber_Value;

        /// <summary>
        /// Gets or sets the value of variable AD1_PI_PhoneNumber_Value.
        /// </summary>
        [TestVariable("fb30261c-a6fd-4758-87cc-d4f70110a9f5")]
        public string AD1_PI_PhoneNumber_Value
        {
            get { return _AD1_PI_PhoneNumber_Value; }
            set { _AD1_PI_PhoneNumber_Value = value; }
        }

        string _AD1_LI_CompanyName;

        /// <summary>
        /// Gets or sets the value of variable AD1_LI_CompanyName.
        /// </summary>
        [TestVariable("3201cf1e-a2f6-4b3b-b4e2-6107be7343ce")]
        public string AD1_LI_CompanyName
        {
            get { return _AD1_LI_CompanyName; }
            set { _AD1_LI_CompanyName = value; }
        }

        string _AD1_LI_PolicyNumber;

        /// <summary>
        /// Gets or sets the value of variable AD1_LI_PolicyNumber.
        /// </summary>
        [TestVariable("61d8a45e-611d-40f0-b652-f23559636636")]
        public string AD1_LI_PolicyNumber
        {
            get { return _AD1_LI_PolicyNumber; }
            set { _AD1_LI_PolicyNumber = value; }
        }

        string _AD1_LI_ClaimNumber;

        /// <summary>
        /// Gets or sets the value of variable AD1_LI_ClaimNumber.
        /// </summary>
        [TestVariable("615e8b5c-4b17-444a-a395-1204ca7140ef")]
        public string AD1_LI_ClaimNumber
        {
            get { return _AD1_LI_ClaimNumber; }
            set { _AD1_LI_ClaimNumber = value; }
        }

        string _AD1_LI_ContactName;

        /// <summary>
        /// Gets or sets the value of variable AD1_LI_ContactName.
        /// </summary>
        [TestVariable("86342f24-ea51-4aec-8258-ab9da2ac69fd")]
        public string AD1_LI_ContactName
        {
            get { return _AD1_LI_ContactName; }
            set { _AD1_LI_ContactName = value; }
        }

        string _AD1_LI_USStateCode;

        /// <summary>
        /// Gets or sets the value of variable AD1_LI_USStateCode.
        /// </summary>
        [TestVariable("9bf3929f-29c8-4008-a029-eecea1cde547")]
        public string AD1_LI_USStateCode
        {
            get { return _AD1_LI_USStateCode; }
            set { _AD1_LI_USStateCode = value; }
        }

        string _AD1_LI_Address1;

        /// <summary>
        /// Gets or sets the value of variable AD1_LI_Address1.
        /// </summary>
        [TestVariable("fd1ffcf4-a2e4-441a-8423-997ee15f0c7b")]
        public string AD1_LI_Address1
        {
            get { return _AD1_LI_Address1; }
            set { _AD1_LI_Address1 = value; }
        }

        string _AD1_LI_Address2;

        /// <summary>
        /// Gets or sets the value of variable AD1_LI_Address2.
        /// </summary>
        [TestVariable("72d30e70-c1e6-4bfe-b9d7-05cdede164f9")]
        public string AD1_LI_Address2
        {
            get { return _AD1_LI_Address2; }
            set { _AD1_LI_Address2 = value; }
        }

        string _AD1_LI_ZipCode;

        /// <summary>
        /// Gets or sets the value of variable AD1_LI_ZipCode.
        /// </summary>
        [TestVariable("97476230-5c0f-44b8-a65f-42404ecab45c")]
        public string AD1_LI_ZipCode
        {
            get { return _AD1_LI_ZipCode; }
            set { _AD1_LI_ZipCode = value; }
        }

        string _AD1_LI_City;

        /// <summary>
        /// Gets or sets the value of variable AD1_LI_City.
        /// </summary>
        [TestVariable("38f0f06d-7d9b-4f59-b42d-7f82f178c643")]
        public string AD1_LI_City
        {
            get { return _AD1_LI_City; }
            set { _AD1_LI_City = value; }
        }

        string _AD1_LI_PhoneUseType;

        /// <summary>
        /// Gets or sets the value of variable AD1_LI_PhoneUseType.
        /// </summary>
        [TestVariable("55e7393e-2e08-4ac1-8d4d-e2969db7be82")]
        public string AD1_LI_PhoneUseType
        {
            get { return _AD1_LI_PhoneUseType; }
            set { _AD1_LI_PhoneUseType = value; }
        }

        string _AD1_LI_PhoneType;

        /// <summary>
        /// Gets or sets the value of variable AD1_LI_PhoneType.
        /// </summary>
        [TestVariable("0249fabb-2c39-4f4e-bc31-8289042b60b8")]
        public string AD1_LI_PhoneType
        {
            get { return _AD1_LI_PhoneType; }
            set { _AD1_LI_PhoneType = value; }
        }

        string _AD1_LI_PhoneSource;

        /// <summary>
        /// Gets or sets the value of variable AD1_LI_PhoneSource.
        /// </summary>
        [TestVariable("d996cee8-c3d9-4469-ab90-785d5767ba72")]
        public string AD1_LI_PhoneSource
        {
            get { return _AD1_LI_PhoneSource; }
            set { _AD1_LI_PhoneSource = value; }
        }

        string _AD1_LI_PhoneNumber;

        /// <summary>
        /// Gets or sets the value of variable AD1_LI_PhoneNumber.
        /// </summary>
        [TestVariable("036ca0e9-47e9-488f-a4a2-c58ba2f37da4")]
        public string AD1_LI_PhoneNumber
        {
            get { return _AD1_LI_PhoneNumber; }
            set { _AD1_LI_PhoneNumber = value; }
        }

        string _AD1_LI_DOB;

        /// <summary>
        /// Gets or sets the value of variable AD1_LI_DOB.
        /// </summary>
        [TestVariable("6b3badea-e63d-4d1e-9d23-7798a8351e6f")]
        public string AD1_LI_DOB
        {
            get { return _AD1_LI_DOB; }
            set { _AD1_LI_DOB = value; }
        }

        string _AD1_LI_LicenseNumber;

        /// <summary>
        /// Gets or sets the value of variable AD1_LI_LicenseNumber.
        /// </summary>
        [TestVariable("1482eaa5-b4ad-4ca8-b05f-a5ae1fdd5e4c")]
        public string AD1_LI_LicenseNumber
        {
            get { return _AD1_LI_LicenseNumber; }
            set { _AD1_LI_LicenseNumber = value; }
        }

        string _AD1_LI_DriversLicenseState;

        /// <summary>
        /// Gets or sets the value of variable AD1_LI_DriversLicenseState.
        /// </summary>
        [TestVariable("ce0fa41b-ee2d-4863-9c7f-1d89ebdac1f1")]
        public string AD1_LI_DriversLicenseState
        {
            get { return _AD1_LI_DriversLicenseState; }
            set { _AD1_LI_DriversLicenseState = value; }
        }

        string _AD1_LI_RevocationDate;

        /// <summary>
        /// Gets or sets the value of variable AD1_LI_RevocationDate.
        /// </summary>
        [TestVariable("994ad1d6-afc8-4c0b-9839-d28be80c985d")]
        public string AD1_LI_RevocationDate
        {
            get { return _AD1_LI_RevocationDate; }
            set { _AD1_LI_RevocationDate = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 720 units.", new RecordItemIndex(0));
            Mouse.ScrollWheel(720);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Address line 1') on item 'ApplicationUnderTest.FooterMappingAddress_line1'.", repo.ApplicationUnderTest.FooterMappingAddress_line1Info, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAddress_line1Info, "InnerText", "Address line 1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -480 units.", new RecordItemIndex(2));
            Mouse.ScrollWheel(-480);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Footer_ClaimInfo' at 50;13.", repo.ApplicationUnderTest.Footer_ClaimInfoInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Footer_ClaimInfo.Click("50;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AdverseInformation1' at 56;6.", repo.ApplicationUnderTest.AdverseInformation1Info, new RecordItemIndex(4));
            repo.ApplicationUnderTest.AdverseInformation1.Click("56;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -120 units.", new RecordItemIndex(5));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 240 units.", new RecordItemIndex(6));
            Mouse.ScrollWheel(240);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.Adverse_Information___AD1_PI_FirstName_AD1_PI_LastName'.", repo.ApplicationUnderTest.Adverse_Information___AD1_PI_FirstName_AD1_PI_LastNameInfo, new RecordItemIndex(7));
            Validate.Exists(repo.ApplicationUnderTest.Adverse_Information___AD1_PI_FirstName_AD1_PI_LastNameInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Adverse_Information___AD1_PI_FirstName_AD1_PI_LastName' at 31;9.", repo.ApplicationUnderTest.Adverse_Information___AD1_PI_FirstName_AD1_PI_LastNameInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.Adverse_Information___AD1_PI_FirstName_AD1_PI_LastName.Click("31;9");
            Delay.Milliseconds(200);
            
            // Adverse Driver - Personal Information
            Report.Log(ReportLevel.Info, "Section", "Adverse Driver - Personal Information", new RecordItemIndex(9));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Driver Information') on item 'ApplicationUnderTest.FooterMappingAD1PIDriverInformation1'.", repo.ApplicationUnderTest.FooterMappingAD1PIDriverInformation1Info, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1PIDriverInformation1Info, "InnerText", "Driver Information");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Adverse Driver Information') on item 'ApplicationUnderTest.FooterMappingAD1PIAdverse_Driver_Information'.", repo.ApplicationUnderTest.FooterMappingAD1PIAdverse_Driver_InformationInfo, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1PIAdverse_Driver_InformationInfo, "InnerText", "Adverse Driver Information");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='First name') on item 'ApplicationUnderTest.FooterMappingFirstName'.", repo.ApplicationUnderTest.FooterMappingFirstNameInfo, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingFirstNameInfo, "InnerText", "First name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_PI_FirstName) on item 'ApplicationUnderTest.FooterMappingAD1PIFirstName'.", repo.ApplicationUnderTest.FooterMappingAD1PIFirstNameInfo, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1PIFirstNameInfo, "InnerText", AD1_PI_FirstName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_PI_FirstName, new RecordItemIndex(14));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Last Name') on item 'ApplicationUnderTest.FooterMappingLastName'.", repo.ApplicationUnderTest.FooterMappingLastNameInfo, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingLastNameInfo, "InnerText", "Last Name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_PI_LastName) on item 'ApplicationUnderTest.FooterMappingAD1PILastName'.", repo.ApplicationUnderTest.FooterMappingAD1PILastNameInfo, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1PILastNameInfo, "InnerText", AD1_PI_LastName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_PI_LastName, new RecordItemIndex(17));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Address line 1') on item 'ApplicationUnderTest.FooterMappingAddress_line1'.", repo.ApplicationUnderTest.FooterMappingAddress_line1Info, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAddress_line1Info, "InnerText", "Address line 1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_PI_Address1) on item 'ApplicationUnderTest.FooterMappingAD1PIAddress1'.", repo.ApplicationUnderTest.FooterMappingAD1PIAddress1Info, new RecordItemIndex(19));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1PIAddress1Info, "InnerText", AD1_PI_Address1);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_PI_Address1, new RecordItemIndex(20));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Address line 2') on item 'ApplicationUnderTest.FooterMappingAddress_line2'.", repo.ApplicationUnderTest.FooterMappingAddress_line2Info, new RecordItemIndex(21));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAddress_line2Info, "InnerText", "Address line 2");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_PI_Address2) on item 'ApplicationUnderTest.FooterMappingAD1PIAddress2'.", repo.ApplicationUnderTest.FooterMappingAD1PIAddress2Info, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1PIAddress2Info, "InnerText", AD1_PI_Address2);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_PI_Address2, new RecordItemIndex(23));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='City') on item 'ApplicationUnderTest.FooterMappingAddress_City'.", repo.ApplicationUnderTest.FooterMappingAddress_CityInfo, new RecordItemIndex(24));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAddress_CityInfo, "InnerText", "City");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_PI_City) on item 'ApplicationUnderTest.FooterMappingAD1PICity'.", repo.ApplicationUnderTest.FooterMappingAD1PICityInfo, new RecordItemIndex(25));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1PICityInfo, "InnerText", AD1_PI_City);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_PI_City, new RecordItemIndex(26));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='State') on item 'ApplicationUnderTest.FooterMappingState'.", repo.ApplicationUnderTest.FooterMappingStateInfo, new RecordItemIndex(27));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingStateInfo, "InnerText", "State");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_PI_State) on item 'ApplicationUnderTest.FooterMappingAD1PIState'.", repo.ApplicationUnderTest.FooterMappingAD1PIStateInfo, new RecordItemIndex(28));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1PIStateInfo, "InnerText", AD1_PI_State);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_PI_State, new RecordItemIndex(29));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Zip') on item 'ApplicationUnderTest.FooterMappingZip'.", repo.ApplicationUnderTest.FooterMappingZipInfo, new RecordItemIndex(30));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingZipInfo, "InnerText", "Zip");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.FooterMappingAD1PIZip' and assigning its value to variable 'AD1_PI_Zip'.", repo.ApplicationUnderTest.FooterMappingAD1PIZipInfo, new RecordItemIndex(31));
            AD1_PI_Zip = repo.ApplicationUnderTest.FooterMappingAD1PIZip.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_PI_Zip) on item 'ApplicationUnderTest.FooterMappingAD1PIZip'.", repo.ApplicationUnderTest.FooterMappingAD1PIZipInfo, new RecordItemIndex(32));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1PIZipInfo, "InnerText", AD1_PI_Zip);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Place Of Employment') on item 'ApplicationUnderTest.FooterMappingPlace_Of_Employment'.", repo.ApplicationUnderTest.FooterMappingPlace_Of_EmploymentInfo, new RecordItemIndex(33));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingPlace_Of_EmploymentInfo, "InnerText", "Place Of Employment");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_PI_POE) on item 'ApplicationUnderTest.FooterMappingAD1_PI_POE'.", repo.ApplicationUnderTest.FooterMappingAD1_PI_POEInfo, new RecordItemIndex(34));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1_PI_POEInfo, "InnerText", AD1_PI_POE);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_PI_POE, new RecordItemIndex(35));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Returned Mail') on item 'ApplicationUnderTest.FooterMappingReturned_Mail'.", repo.ApplicationUnderTest.FooterMappingReturned_MailInfo, new RecordItemIndex(36));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingReturned_MailInfo, "InnerText", "Returned Mail");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_PI_Zip, new RecordItemIndex(37));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Bankruptcy') on item 'ApplicationUnderTest.FooterMappingBankruptcy'.", repo.ApplicationUnderTest.FooterMappingBankruptcyInfo, new RecordItemIndex(38));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingBankruptcyInfo, "InnerText", "Bankruptcy");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Bankruptcy County') on item 'ApplicationUnderTest.FooterMappingBankruptcyCounty'.", repo.ApplicationUnderTest.FooterMappingBankruptcyCountyInfo, new RecordItemIndex(39));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingBankruptcyCountyInfo, "InnerText", "Bankruptcy County");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_PI_BankruptcyCounty) on item 'ApplicationUnderTest.FooterMappingAD1_PI_BankruptcyCounty'.", repo.ApplicationUnderTest.FooterMappingAD1_PI_BankruptcyCountyInfo, new RecordItemIndex(40));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1_PI_BankruptcyCountyInfo, "InnerText", AD1_PI_BankruptcyCounty);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_PI_BankruptcyCounty, new RecordItemIndex(41));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Bankruptcy District') on item 'ApplicationUnderTest.FooterMappingBankruptcyDistrict'.", repo.ApplicationUnderTest.FooterMappingBankruptcyDistrictInfo, new RecordItemIndex(42));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingBankruptcyDistrictInfo, "InnerText", "Bankruptcy District");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_PI_BankruptcyDistrict) on item 'ApplicationUnderTest.FooterMappingAD1_PI_BankruptcyDistrict'.", repo.ApplicationUnderTest.FooterMappingAD1_PI_BankruptcyDistrictInfo, new RecordItemIndex(43));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1_PI_BankruptcyDistrictInfo, "InnerText", AD1_PI_BankruptcyDistrict);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_PI_BankruptcyDistrict, new RecordItemIndex(44));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Bankruptcy Chapter') on item 'ApplicationUnderTest.FooterMappingBankruptcyChapter'.", repo.ApplicationUnderTest.FooterMappingBankruptcyChapterInfo, new RecordItemIndex(45));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingBankruptcyChapterInfo, "InnerText", "Bankruptcy Chapter");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_PI_BankruptcyChapter) on item 'ApplicationUnderTest.FooterMappingAD1_PI_BankruptcyChapter'.", repo.ApplicationUnderTest.FooterMappingAD1_PI_BankruptcyChapterInfo, new RecordItemIndex(46));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1_PI_BankruptcyChapterInfo, "InnerText", AD1_PI_BankruptcyChapter);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_PI_BankruptcyChapter, new RecordItemIndex(47));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Bankruptcy Case No') on item 'ApplicationUnderTest.FooterMappingBankruptcyCaseNo'.", repo.ApplicationUnderTest.FooterMappingBankruptcyCaseNoInfo, new RecordItemIndex(48));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingBankruptcyCaseNoInfo, "InnerText", "Bankruptcy Case No");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_PI_BankruptcyCaseNo) on item 'ApplicationUnderTest.FooterMappingAD1_PI_BankruptcyCaseNo'.", repo.ApplicationUnderTest.FooterMappingAD1_PI_BankruptcyCaseNoInfo, new RecordItemIndex(49));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1_PI_BankruptcyCaseNoInfo, "InnerText", AD1_PI_BankruptcyCaseNo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_PI_BankruptcyCaseNo, new RecordItemIndex(50));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Phone/Fax Information') on item 'ApplicationUnderTest.FooterMappingAD1PIPhoneInformation'.", repo.ApplicationUnderTest.FooterMappingAD1PIPhoneInformationInfo, new RecordItemIndex(51));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1PIPhoneInformationInfo, "InnerText", "Phone/Fax Information");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Use Type') on item 'ApplicationUnderTest.FooterMappingAD1PIUseType'.", repo.ApplicationUnderTest.FooterMappingAD1PIUseTypeInfo, new RecordItemIndex(52));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1PIUseTypeInfo, "InnerText", "Use Type");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.FooterMappingAD1PIPersonal' and assigning its value to variable 'AD1_PI_Personal'.", repo.ApplicationUnderTest.FooterMappingAD1PIPersonalInfo, new RecordItemIndex(53));
            AD1_PI_Personal = repo.ApplicationUnderTest.FooterMappingAD1PIPersonal.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_PI_Personal) on item 'ApplicationUnderTest.FooterMappingAD1PIPersonal'.", repo.ApplicationUnderTest.FooterMappingAD1PIPersonalInfo, new RecordItemIndex(54));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1PIPersonalInfo, "InnerText", AD1_PI_Personal);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_PI_Personal, new RecordItemIndex(55));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Phone Type') on item 'ApplicationUnderTest.FooterMappingAD1PIPhoneType'.", repo.ApplicationUnderTest.FooterMappingAD1PIPhoneTypeInfo, new RecordItemIndex(56));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1PIPhoneTypeInfo, "InnerText", "Phone Type");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.FooterMappingAD1_PI_PhoneType_LandLine' and assigning its value to variable 'AD1_PI_PhoneType_LandLine'.", repo.ApplicationUnderTest.FooterMappingAD1_PI_PhoneType_LandLineInfo, new RecordItemIndex(57));
            AD1_PI_PhoneType_LandLine = repo.ApplicationUnderTest.FooterMappingAD1_PI_PhoneType_LandLine.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_PI_PhoneType_LandLine) on item 'ApplicationUnderTest.FooterMappingAD1_PI_PhoneType_LandLine'.", repo.ApplicationUnderTest.FooterMappingAD1_PI_PhoneType_LandLineInfo, new RecordItemIndex(58));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1_PI_PhoneType_LandLineInfo, "InnerText", AD1_PI_PhoneType_LandLine);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_PI_PhoneType_LandLine, new RecordItemIndex(59));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Source') on item 'ApplicationUnderTest.FooterMappingAD1PISource'.", repo.ApplicationUnderTest.FooterMappingAD1PISourceInfo, new RecordItemIndex(60));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1PISourceInfo, "InnerText", "Source");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.FooterMappingAD1PIDirect' and assigning its value to variable 'AD1_PI_Direct'.", repo.ApplicationUnderTest.FooterMappingAD1PIDirectInfo, new RecordItemIndex(61));
            AD1_PI_Direct = repo.ApplicationUnderTest.FooterMappingAD1PIDirect.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_PI_Direct) on item 'ApplicationUnderTest.FooterMappingAD1PIDirect'.", repo.ApplicationUnderTest.FooterMappingAD1PIDirectInfo, new RecordItemIndex(62));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1PIDirectInfo, "InnerText", AD1_PI_Direct);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_PI_Direct, new RecordItemIndex(63));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Phone number') on item 'ApplicationUnderTest.FooterMappingAD1PIPhoneNumber'.", repo.ApplicationUnderTest.FooterMappingAD1PIPhoneNumberInfo, new RecordItemIndex(64));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1PIPhoneNumberInfo, "InnerText", "Phone number");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.FooterMappingAD1PIPhoneNumber_Value' and assigning its value to variable 'AD1_PI_PhoneNumber_Value'.", repo.ApplicationUnderTest.FooterMappingAD1PIPhoneNumber_ValueInfo, new RecordItemIndex(65));
            AD1_PI_PhoneNumber_Value = repo.ApplicationUnderTest.FooterMappingAD1PIPhoneNumber_Value.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_PI_PhoneNumber_Value) on item 'ApplicationUnderTest.FooterMappingAD1PIPhoneNumber_Value'.", repo.ApplicationUnderTest.FooterMappingAD1PIPhoneNumber_ValueInfo, new RecordItemIndex(66));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1PIPhoneNumber_ValueInfo, "InnerText", AD1_PI_PhoneNumber_Value);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_PI_PhoneNumber_Value, new RecordItemIndex(67));
            
            // Adverse Driver 1 - Insurance Information
            Report.Log(ReportLevel.Info, "Section", "Adverse Driver 1 - Insurance Information", new RecordItemIndex(68));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Insurance Information') on item 'ApplicationUnderTest.FooterMappingInsuranceInformation2'.", repo.ApplicationUnderTest.FooterMappingInsuranceInformation2Info, new RecordItemIndex(69));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingInsuranceInformation2Info, "InnerText", "Insurance Information");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Insurance Company') on item 'ApplicationUnderTest.FooterMappingInsurance_Company'.", repo.ApplicationUnderTest.FooterMappingInsurance_CompanyInfo, new RecordItemIndex(70));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingInsurance_CompanyInfo, "InnerText", "Insurance Company");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_LI_CompanyName) on item 'ApplicationUnderTest.FooterMappingTRANSGUARDINSURANCE'.", repo.ApplicationUnderTest.FooterMappingTRANSGUARDINSURANCEInfo, new RecordItemIndex(71));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingTRANSGUARDINSURANCEInfo, "InnerText", AD1_LI_CompanyName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_LI_CompanyName, new RecordItemIndex(72));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Policy Number') on item 'ApplicationUnderTest.FooterMappingPolicy_Number'.", repo.ApplicationUnderTest.FooterMappingPolicy_NumberInfo, new RecordItemIndex(73));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingPolicy_NumberInfo, "InnerText", "Policy Number");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_LI_PolicyNumber) on item 'ApplicationUnderTest.FooterMappingAD1PolicyNumber1'.", repo.ApplicationUnderTest.FooterMappingAD1PolicyNumber1Info, new RecordItemIndex(74));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1PolicyNumber1Info, "InnerText", AD1_LI_PolicyNumber);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_LI_PolicyNumber, new RecordItemIndex(75));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Claim Number') on item 'ApplicationUnderTest.FooterMappingClaim_Number'.", repo.ApplicationUnderTest.FooterMappingClaim_NumberInfo, new RecordItemIndex(76));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingClaim_NumberInfo, "InnerText", "Claim Number");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_LI_ClaimNumber) on item 'ApplicationUnderTest.FooterMappingAD1ClaimNumber1'.", repo.ApplicationUnderTest.FooterMappingAD1ClaimNumber1Info, new RecordItemIndex(77));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1ClaimNumber1Info, "InnerText", AD1_LI_ClaimNumber);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_LI_ClaimNumber, new RecordItemIndex(78));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Adjuster Information') on item 'ApplicationUnderTest.FooterMappingAdjusterInformation'.", repo.ApplicationUnderTest.FooterMappingAdjusterInformationInfo, new RecordItemIndex(79));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAdjusterInformationInfo, "InnerText", "Adjuster Information");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Contact Name') on item 'ApplicationUnderTest.FooterMappingContact_Name'.", repo.ApplicationUnderTest.FooterMappingContact_NameInfo, new RecordItemIndex(80));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingContact_NameInfo, "InnerText", "Contact Name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_LI_ContactName) on item 'ApplicationUnderTest.FooterMappingAD1LIContactName'.", repo.ApplicationUnderTest.FooterMappingAD1LIContactNameInfo, new RecordItemIndex(81));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1LIContactNameInfo, "InnerText", AD1_LI_ContactName);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_LI_ContactName, new RecordItemIndex(82));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='State') on item 'ApplicationUnderTest.FooterMappingState'.", repo.ApplicationUnderTest.FooterMappingStateInfo, new RecordItemIndex(83));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingStateInfo, "InnerText", "State");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.FooterMappingAD1LIState' and assigning its value to variable 'AD1_LI_USStateCode'.", repo.ApplicationUnderTest.FooterMappingAD1LIStateInfo, new RecordItemIndex(84));
            AD1_LI_USStateCode = repo.ApplicationUnderTest.FooterMappingAD1LIState.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_LI_USStateCode) on item 'ApplicationUnderTest.FooterMappingAD1LIState'.", repo.ApplicationUnderTest.FooterMappingAD1LIStateInfo, new RecordItemIndex(85));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1LIStateInfo, "InnerText", AD1_LI_USStateCode);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_LI_USStateCode, new RecordItemIndex(86));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Address1') on item 'ApplicationUnderTest.FooterMappingAddress1'.", repo.ApplicationUnderTest.FooterMappingAddress1Info, new RecordItemIndex(87));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAddress1Info, "InnerText", "Address1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_LI_Address1) on item 'ApplicationUnderTest.FooterMappingAD1LIAddress1'.", repo.ApplicationUnderTest.FooterMappingAD1LIAddress1Info, new RecordItemIndex(88));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1LIAddress1Info, "InnerText", AD1_LI_Address1);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_LI_Address1, new RecordItemIndex(89));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Address2') on item 'ApplicationUnderTest.FooterMappingAddress2'.", repo.ApplicationUnderTest.FooterMappingAddress2Info, new RecordItemIndex(90));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAddress2Info, "InnerText", "Address2");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_LI_Address2) on item 'ApplicationUnderTest.FooterMappingAD1LIAddress2'.", repo.ApplicationUnderTest.FooterMappingAD1LIAddress2Info, new RecordItemIndex(91));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1LIAddress2Info, "InnerText", AD1_LI_Address2);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_LI_Address2, new RecordItemIndex(92));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Zip') on item 'ApplicationUnderTest.FooterMappingZip'.", repo.ApplicationUnderTest.FooterMappingZipInfo, new RecordItemIndex(93));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingZipInfo, "InnerText", "Zip");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.FooterMappingAD1LIZip' and assigning its value to variable 'AD1_LI_ZipCode'.", repo.ApplicationUnderTest.FooterMappingAD1LIZipInfo, new RecordItemIndex(94));
            AD1_LI_ZipCode = repo.ApplicationUnderTest.FooterMappingAD1LIZip.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_LI_ZipCode) on item 'ApplicationUnderTest.FooterMappingAD1LIZip'.", repo.ApplicationUnderTest.FooterMappingAD1LIZipInfo, new RecordItemIndex(95));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1LIZipInfo, "InnerText", AD1_LI_ZipCode);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_LI_ZipCode, new RecordItemIndex(96));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='City') on item 'ApplicationUnderTest.FooterMappingAddress_City'.", repo.ApplicationUnderTest.FooterMappingAddress_CityInfo, new RecordItemIndex(97));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAddress_CityInfo, "InnerText", "City");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_LI_City) on item 'ApplicationUnderTest.FooterMappingAD1LICity'.", repo.ApplicationUnderTest.FooterMappingAD1LICityInfo, new RecordItemIndex(98));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1LICityInfo, "InnerText", AD1_LI_City);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_LI_City, new RecordItemIndex(99));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Phone/Fax Information') on item 'ApplicationUnderTest.FooterMappingAD1LIPhoneInformation'.", repo.ApplicationUnderTest.FooterMappingAD1LIPhoneInformationInfo, new RecordItemIndex(100));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1LIPhoneInformationInfo, "InnerText", "Phone/Fax Information");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Use Type') on item 'ApplicationUnderTest.FooterMappingAD1LIUseType'.", repo.ApplicationUnderTest.FooterMappingAD1LIUseTypeInfo, new RecordItemIndex(101));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1LIUseTypeInfo, "InnerText", "Use Type");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.FooterMappingAD1LIBusiness' and assigning its value to variable 'AD1_LI_PhoneUseType'.", repo.ApplicationUnderTest.FooterMappingAD1LIBusinessInfo, new RecordItemIndex(102));
            AD1_LI_PhoneUseType = repo.ApplicationUnderTest.FooterMappingAD1LIBusiness.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_LI_PhoneUseType) on item 'ApplicationUnderTest.FooterMappingAD1LIBusiness'.", repo.ApplicationUnderTest.FooterMappingAD1LIBusinessInfo, new RecordItemIndex(103));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1LIBusinessInfo, "InnerText", AD1_LI_PhoneUseType);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_LI_PhoneUseType, new RecordItemIndex(104));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Phone Type') on item 'ApplicationUnderTest.FooterMappingAD1LIPhoneType'.", repo.ApplicationUnderTest.FooterMappingAD1LIPhoneTypeInfo, new RecordItemIndex(105));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1LIPhoneTypeInfo, "InnerText", "Phone Type");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.FooterMappingAD1LICell' and assigning its value to variable 'AD1_LI_PhoneType'.", repo.ApplicationUnderTest.FooterMappingAD1LICellInfo, new RecordItemIndex(106));
            AD1_LI_PhoneType = repo.ApplicationUnderTest.FooterMappingAD1LICell.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_LI_PhoneType) on item 'ApplicationUnderTest.FooterMappingAD1LICell'.", repo.ApplicationUnderTest.FooterMappingAD1LICellInfo, new RecordItemIndex(107));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1LICellInfo, "InnerText", AD1_LI_PhoneType);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_LI_PhoneType, new RecordItemIndex(108));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Source') on item 'ApplicationUnderTest.FooterMappingAD1LISource'.", repo.ApplicationUnderTest.FooterMappingAD1LISourceInfo, new RecordItemIndex(109));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1LISourceInfo, "InnerText", "Source");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_LI_PhoneSource, new RecordItemIndex(110));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_LI_PhoneSource) on item 'ApplicationUnderTest.FooterMappingAD1LISkipTrace'.", repo.ApplicationUnderTest.FooterMappingAD1LISkipTraceInfo, new RecordItemIndex(111));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1LISkipTraceInfo, "InnerText", AD1_LI_PhoneSource);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.FooterMappingAD1LISkipTrace' and assigning its value to variable 'AD1_LI_PhoneSource'.", repo.ApplicationUnderTest.FooterMappingAD1LISkipTraceInfo, new RecordItemIndex(112));
            AD1_LI_PhoneSource = repo.ApplicationUnderTest.FooterMappingAD1LISkipTrace.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Phone number') on item 'ApplicationUnderTest.FooterMappingAD1LIPhoneNumber1'.", repo.ApplicationUnderTest.FooterMappingAD1LIPhoneNumber1Info, new RecordItemIndex(113));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1LIPhoneNumber1Info, "InnerText", "Phone number");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.FooterMappingAD1LIPhoneNumber' and assigning its value to variable 'AD1_LI_PhoneNumber'.", repo.ApplicationUnderTest.FooterMappingAD1LIPhoneNumberInfo, new RecordItemIndex(114));
            AD1_LI_PhoneNumber = repo.ApplicationUnderTest.FooterMappingAD1LIPhoneNumber.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_LI_PhoneNumber) on item 'ApplicationUnderTest.FooterMappingAD1LIPhoneNumber'.", repo.ApplicationUnderTest.FooterMappingAD1LIPhoneNumberInfo, new RecordItemIndex(115));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1LIPhoneNumberInfo, "InnerText", AD1_LI_PhoneNumber);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_LI_PhoneNumber, new RecordItemIndex(116));
            
            // Adverse Driver 1 - Attorney Information
            Report.Log(ReportLevel.Info, "Section", "Adverse Driver 1 - Attorney Information", new RecordItemIndex(117));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Attorney Information') on item 'ApplicationUnderTest.FooterMappingAttorneyInformation'.", repo.ApplicationUnderTest.FooterMappingAttorneyInformationInfo, new RecordItemIndex(118));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAttorneyInformationInfo, "InnerText", "Attorney Information");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Firm Name') on item 'ApplicationUnderTest.FooterMappingFirm_Name'.", repo.ApplicationUnderTest.FooterMappingFirm_NameInfo, new RecordItemIndex(119));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingFirm_NameInfo, "InnerText", "Firm Name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='AD_Attorney_FirmName') on item 'ApplicationUnderTest.FooterMappingAD1AttorneyFirmName'.", repo.ApplicationUnderTest.FooterMappingAD1AttorneyFirmNameInfo, new RecordItemIndex(120));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1AttorneyFirmNameInfo, "InnerText", "AD_Attorney_FirmName");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "AD_Attorney_FirmName", new RecordItemIndex(121));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='First name') on item 'ApplicationUnderTest.FooterMappingFirstName'.", repo.ApplicationUnderTest.FooterMappingFirstNameInfo, new RecordItemIndex(122));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingFirstNameInfo, "InnerText", "First name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='AD_Attorney_FirstName') on item 'ApplicationUnderTest.FooterMappingAD1AttorneyFirstName'.", repo.ApplicationUnderTest.FooterMappingAD1AttorneyFirstNameInfo, new RecordItemIndex(123));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1AttorneyFirstNameInfo, "InnerText", "AD_Attorney_FirstName");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "AD_Attorney_FirstName", new RecordItemIndex(124));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Last Name') on item 'ApplicationUnderTest.FooterMappingLastName'.", repo.ApplicationUnderTest.FooterMappingLastNameInfo, new RecordItemIndex(125));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingLastNameInfo, "InnerText", "Last Name");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='AD_Attorney_LastName') on item 'ApplicationUnderTest.FooterMappingAD1AttorneyLastName'.", repo.ApplicationUnderTest.FooterMappingAD1AttorneyLastNameInfo, new RecordItemIndex(126));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1AttorneyLastNameInfo, "InnerText", "AD_Attorney_LastName");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "AD_Attorney_LastName", new RecordItemIndex(127));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Representation Date') on item 'ApplicationUnderTest.FooterMappingRepresentationDate'.", repo.ApplicationUnderTest.FooterMappingRepresentationDateInfo, new RecordItemIndex(128));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingRepresentationDateInfo, "InnerText", "Representation Date");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='02/02/19') on item 'ApplicationUnderTest.FooterMappingAD1AttorneyRepresentation_Date'.", repo.ApplicationUnderTest.FooterMappingAD1AttorneyRepresentation_DateInfo, new RecordItemIndex(129));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1AttorneyRepresentation_DateInfo, "InnerText", "02/02/19");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "02/02/19", new RecordItemIndex(130));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Address Info') on item 'ApplicationUnderTest.AddressInfo'.", repo.ApplicationUnderTest.AddressInfoInfo, new RecordItemIndex(131));
            Validate.AttributeEqual(repo.ApplicationUnderTest.AddressInfoInfo, "InnerText", "Address Info");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Address1') on item 'ApplicationUnderTest.FooterMappingAddress1'.", repo.ApplicationUnderTest.FooterMappingAddress1Info, new RecordItemIndex(132));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAddress1Info, "InnerText", "Address1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='AD_Attorney_Address1') on item 'ApplicationUnderTest.FooterMappingAD1AttorneyAddress1'.", repo.ApplicationUnderTest.FooterMappingAD1AttorneyAddress1Info, new RecordItemIndex(133));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1AttorneyAddress1Info, "InnerText", "AD_Attorney_Address1");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "AD_Attorney_Address1", new RecordItemIndex(134));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Address2') on item 'ApplicationUnderTest.FooterMappingAddress2'.", repo.ApplicationUnderTest.FooterMappingAddress2Info, new RecordItemIndex(135));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAddress2Info, "InnerText", "Address2");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='AD_Attorney_Address2') on item 'ApplicationUnderTest.FooterMappingAD1AttorneyAddress2'.", repo.ApplicationUnderTest.FooterMappingAD1AttorneyAddress2Info, new RecordItemIndex(136));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1AttorneyAddress2Info, "InnerText", "AD_Attorney_Address2");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "AD_Attorney_Address2", new RecordItemIndex(137));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='City') on item 'ApplicationUnderTest.FooterMappingAddress_City'.", repo.ApplicationUnderTest.FooterMappingAddress_CityInfo, new RecordItemIndex(138));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAddress_CityInfo, "InnerText", "City");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='AD_Attorney_City') on item 'ApplicationUnderTest.FooterMappingAD1AttorneyCity'.", repo.ApplicationUnderTest.FooterMappingAD1AttorneyCityInfo, new RecordItemIndex(139));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1AttorneyCityInfo, "InnerText", "AD_Attorney_City");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "AD_Attorney_City", new RecordItemIndex(140));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='State') on item 'ApplicationUnderTest.FooterMappingState'.", repo.ApplicationUnderTest.FooterMappingStateInfo, new RecordItemIndex(141));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingStateInfo, "InnerText", "State");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='LA') on item 'ApplicationUnderTest.FooterMappingAD1AttorneyState'.", repo.ApplicationUnderTest.FooterMappingAD1AttorneyStateInfo, new RecordItemIndex(142));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1AttorneyStateInfo, "InnerText", "LA");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "LA", new RecordItemIndex(143));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Zip') on item 'ApplicationUnderTest.FooterMappingZip'.", repo.ApplicationUnderTest.FooterMappingZipInfo, new RecordItemIndex(144));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingZipInfo, "InnerText", "Zip");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='12345-5432') on item 'ApplicationUnderTest.FooterMappingAD1AttorneyZip'.", repo.ApplicationUnderTest.FooterMappingAD1AttorneyZipInfo, new RecordItemIndex(145));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1AttorneyZipInfo, "InnerText", "12345-5432");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "12345-5432", new RecordItemIndex(146));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Email ID') on item 'ApplicationUnderTest.FooterMappingEmail'.", repo.ApplicationUnderTest.FooterMappingEmailInfo, new RecordItemIndex(147));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingEmailInfo, "InnerText", "Email ID");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(148));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Phone/Fax Information') on item 'ApplicationUnderTest.FooterMappingPhoneInformation2'.", repo.ApplicationUnderTest.FooterMappingPhoneInformation2Info, new RecordItemIndex(149));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingPhoneInformation2Info, "InnerText", "Phone/Fax Information");
            Delay.Milliseconds(100);
            
            // Adverse Driver 1 - License Information
            Report.Log(ReportLevel.Info, "Section", "Adverse Driver 1 - License Information", new RecordItemIndex(150));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='License Information') on item 'ApplicationUnderTest.LicenseInformation2'.", repo.ApplicationUnderTest.LicenseInformation2Info, new RecordItemIndex(151));
            Validate.AttributeEqual(repo.ApplicationUnderTest.LicenseInformation2Info, "InnerText", "License Information");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='SSN') on item 'ApplicationUnderTest.FooterMappingSSN'.", repo.ApplicationUnderTest.FooterMappingSSNInfo, new RecordItemIndex(152));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingSSNInfo, "InnerText", "SSN");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='XXX-XX-1SSN') on item 'ApplicationUnderTest.FooterMappingAD1_LI_LicenseSSN'.", repo.ApplicationUnderTest.FooterMappingAD1_LI_LicenseSSNInfo, new RecordItemIndex(153));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1_LI_LicenseSSNInfo, "InnerText", "XXX-XX-1SSN");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", "XXX-XX-1SSN", new RecordItemIndex(154));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Date of Birth') on item 'ApplicationUnderTest.FooterMappingAD1_LI_LicenseDateofBirth'.", repo.ApplicationUnderTest.FooterMappingAD1_LI_LicenseDateofBirthInfo, new RecordItemIndex(155));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1_LI_LicenseDateofBirthInfo, "InnerText", "Date of Birth");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.FooterMappingAD1_LI_LicenseDOB' and assigning its value to variable 'AD1_LI_DOB'.", repo.ApplicationUnderTest.FooterMappingAD1_LI_LicenseDOBInfo, new RecordItemIndex(156));
            AD1_LI_DOB = repo.ApplicationUnderTest.FooterMappingAD1_LI_LicenseDOB.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_LI_DOB, new RecordItemIndex(157));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_LI_DOB) on item 'ApplicationUnderTest.FooterMappingAD1_LI_LicenseDOB'.", repo.ApplicationUnderTest.FooterMappingAD1_LI_LicenseDOBInfo, new RecordItemIndex(158));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1_LI_LicenseDOBInfo, "InnerText", AD1_LI_DOB);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Drivers License Number') on item 'ApplicationUnderTest.FooterMappingDrivers_License_Number'.", repo.ApplicationUnderTest.FooterMappingDrivers_License_NumberInfo, new RecordItemIndex(159));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingDrivers_License_NumberInfo, "InnerText", "Drivers License Number");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_LI_LicenseNumber) on item 'ApplicationUnderTest.FooterMappingAD1LILicenseNumber'.", repo.ApplicationUnderTest.FooterMappingAD1LILicenseNumberInfo, new RecordItemIndex(160));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1LILicenseNumberInfo, "InnerText", AD1_LI_LicenseNumber);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_LI_LicenseNumber, new RecordItemIndex(161));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Drivers License State') on item 'ApplicationUnderTest.FooterMappingDrivers_License_State'.", repo.ApplicationUnderTest.FooterMappingDrivers_License_StateInfo, new RecordItemIndex(162));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingDrivers_License_StateInfo, "InnerText", "Drivers License State");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_LI_DriversLicenseState) on item 'ApplicationUnderTest.FooterMappingAD1_LI_LicenseDriverState'.", repo.ApplicationUnderTest.FooterMappingAD1_LI_LicenseDriverStateInfo, new RecordItemIndex(163));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1_LI_LicenseDriverStateInfo, "InnerText", AD1_LI_DriversLicenseState);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "User", AD1_LI_DriversLicenseState, new RecordItemIndex(164));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Revocation Date') on item 'ApplicationUnderTest.FooterMappingRevocationDate'.", repo.ApplicationUnderTest.FooterMappingRevocationDateInfo, new RecordItemIndex(165));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingRevocationDateInfo, "InnerText", "Revocation Date");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ApplicationUnderTest.FooterMappingAD1_LI_RevocationDate' and assigning its value to variable 'AD1_LI_RevocationDate'.", repo.ApplicationUnderTest.FooterMappingAD1_LI_RevocationDateInfo, new RecordItemIndex(166));
            AD1_LI_RevocationDate = repo.ApplicationUnderTest.FooterMappingAD1_LI_RevocationDate.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", AD1_LI_RevocationDate, new RecordItemIndex(167));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$AD1_LI_RevocationDate) on item 'ApplicationUnderTest.FooterMappingAD1_LI_RevocationDate'.", repo.ApplicationUnderTest.FooterMappingAD1_LI_RevocationDateInfo, new RecordItemIndex(168));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingAD1_LI_RevocationDateInfo, "InnerText", AD1_LI_RevocationDate);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Revoked') on item 'ApplicationUnderTest.FooterMappingRevoked'.", repo.ApplicationUnderTest.FooterMappingRevokedInfo, new RecordItemIndex(169));
            Validate.AttributeEqual(repo.ApplicationUnderTest.FooterMappingRevokedInfo, "InnerText", "Revoked");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
